name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: MONGO_URI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            bash -ic '
              source ~/.bashrc || true
              cd eventmanagementapp
              git pull
            
              cd backend
              bun install
              bun run build

              cd ../frontend
              bun install
              bun run build
              
              pm2 restart all
            '
